name: handbrake-jz
version: 1.0.7-1
epoch: 2
summary: HandBrake is a tool for convertion video to.
description: |
  HandBrake is a tool for converting video from nearly any format to a
  selection of modern, widely supported codecs.

grade: stable
confinement: strict

# https://bazaar.launchpad.net/~ubuntu-desktop/+junk/ghex-snap-gnome-3-24/view/head:/snapcraft.yaml

parts:
  desktop-gnome-platform:
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    source: https://github.com/kenvandine/snapcraft-desktop-helpers.git
    source-branch: gnome-3-24
    install: mkdir -p $SNAPCRAFT_PART_INSTALL/gnome-platform

apps:
  ghb:
    command: desktop-launch ghb
    plugs: [unity7, home, gsettings, mount-observe, network, process-control]

parts:
  ghb:
    plugin: inbuild
    configflags:
      - --prefix=/
      - --disable-gtk-update-checks
    source: https://handbrake.fr/rotation.php?file=HandBrake-1.0.7.tar.bz2
    build-packages:
      - g++
      - libtool-bin
      - intltool
      - yasm
      - cmake
      - libgudev-1.0-dev
      - libbz2-dev
      - zlib1g-dev
      - libgtk-3-dev
      - libwebkitgtk-3.0-dev
      - libnotify-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libappindicator3-dev
      - libfribidi-dev
      - libxml2-dev
      - libogg-dev
      - libtheora-dev
      - libvorbis-dev
      - libopus-dev
      - libsamplerate0-dev
      - libfreetype6-dev
      - libfontconfig1-dev
      - libass-dev
      - libmp3lame-dev
      - libx264-dev
      - libjansson-dev
    stage-packages:
      - libmirclient9
    prime:
      - -share/applications

  # https://bazaar.launchpad.net/~ubuntu-desktop/+junk/ghex-snap-gnome-3-24/view/head:/snapcraft.yaml

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    stage-packages:
      - libgtk-3-0
    prime:
      - "-*"
